### ISSUE TITLE
Bracket highlighting suggestion

### ISSUE THREAD

**Issue by jsoto04** [niccord/BracketsCheck#11]
I would like to suggest editing the code to highlight matching and unmatching brackets in different colors.
For example:
(this would be considered matching, therefore these brackets would be highlighted in green)
(these brackets would be highlighted in red, because they don't match.
Thanks for the awesome program BTW

**Comment by niccord** [comment]
Thanks for the suggestion
I don't know if notepad++ APIs allow me to do such a thing.

Also, in this case:
`[(some text]`
is the closing square bracket or the opening round bracket the wrong one?

What if I have a closing one after, like this:
`[(some text] also here) maybe here too]`

I think this is kind of tricky 🙂

I have to think about that.

**Comment by jsoto04** [comment]
In the first example,
`[(some text]`
the round bracket would be incorrect

In the second example,
`[(some text] also here) maybe here too]`
the ones incorrect would be in asterisks:
`[*(*some text] also here*)* maybe here too*]*`
because the pair should be in the same bracket group,for example:
`[this (would be) correct]`,
`[but this(would not]be correct)`

I agree this is a difficult problem, but i also think that you could easily build off of existing software in your program to make it easier.

Also, i think building off of the notepad ++ bracket-pair-highlighting software might make things a bit easier.

Your humble github coder-in-training,
jsoto04 :sunglasses::sunglasses:

**Comment by niccord** [comment]
In my second example, the incorrect brackets can be:
`[*(*some text] also here*)* maybe here too*]*`
as you pointed out, but also:
`[(some text*]* also here) maybe here too]`

As I said, I found this a little bit tricky and I don't want to give wrong info to the user.

Anyway, brackets-pair-highlighting is a built-in feature and I am not sure I can change (part of its) behaviour with a plugin.
Do you @jsoto04 or anyone have some hint about it?

**Comment by jsoto04** [comment]
The second example would not apply actually, because the software finds the first pair first:
`[(some text]`
so the second square bracket:
`maybe here too]`
would be incorrect.

Also, I would suggest not changing the notepad ++ software, but instead maybe copying a portion to use for bracket highlighting.

As for who to ask, I am not the best person to ask for the coding portion. I can code somewhat, but not enough to be of any use to you. The only thing i can code very well is one of those really good calculators with the graphs and whatnot.:laughing::laughing::laughing:

Your humble github coder-in-training,
jsoto04 😎😎

**Comment by niccord** [comment]
Definitively not possible
