### ISSUE TITLE
Hello. Why does it show an error?

### ISSUE THREAD

**Issue by mr-bobich** [niccord/BracketsCheck#18]
StringBuilder builder = new StringBuilder();
builder.Append ("{ Color = ");
builder.Append(" }");

**Comment by niccord** [comment]
Hi @mr-bobich,

This plugin was created to check large SQL files and then extended to all text files.

Since the open curly bracket is followed by a closed round bracket, the algorithm thinks you missed a closed curly bracket.

To avoid this you can try disabling the curly bracket check.

Cheers.

**Comment by mr-bobich** [comment]
Thanks a lot for answer.
