### ISSUE TITLE
Fix char count tab

### ISSUE THREAD

**Issue by niccord** [niccord/BracketsCheck#2]
Tab is managed in different ways: 1 char or 3/4 chars. It affects char count.

**Comment by admiralblair** [comment]
Is this the only bug that affects the character count? I removed all tabs in my document and still the count is off. It gives a line, say 500, and character 30 - but it is a line with only 3 characters on it and no blank space.

**Comment by niccord** [comment]
Can you give a file example? Do you have special char sequences? Like \r \n \t, etc.
