### ISSUE TITLE
Not compatible with x64 build

### ISSUE THREAD

**Issue by niccord** [niccord/BracketsCheck#3]
The plugin works fine with 7.0 version x86 build but doesn't with x64 build.
%1 not a valid Win32 application

**Comment by chcg** [comment]
See PR #4 as starting point for a x64 build.

**Comment by x9t9** [comment]
Yep. also would be great to know ( in readme ) what is the min. version requirement and compatibility. ( e.g. unicode / ansi / x64 / x  ... etc )
Looks like a great plugin though ( even though I could not check because of 64bit ( portable - unicode  ) version

**Comment by chcg** [comment]
@niccord See https://ci.appveyor.com/project/chcg/bracketscheck/builds/25238942/job/vc7e7w3gxv6suygw/artifacts for a x64 version of your plugin.

**Comment by chcg** [comment]
@niccord Could be closed with https://github.com/niccord/BracketsCheck/releases/tag/v1.2.2

**Comment by niccord** [comment]
thank you @chcg :)
