### ISSUE TITLE
BracketsCheck Plugin Crashing Notepad++ on exit

### ISSUE THREAD

**Issue by Zardozz** [niccord/BracketsCheck#5]
I noticed recently that in and updated version of notepad++ that windows was reporting a crash when Notepad++ was closed. I ran notepad++ with -noPlugin and it did not crash.
I disabled the plugins one by one and removing BracketsCheck plugin stopped windows reporting a crash on exit

NotePad ++ Debug info:-
Notepad++ v7.3.2   (32-bit)
Build time : Feb 12 2017 - 23:15:39
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : BracketsCheck.dll DSpellCheck2.dll HTMLTag_unicode.dll ImgTag.dll JSLintNpp.dll mimeTools.dll NamedBookmarks.dll NppConverter.dll NppExport.dll NppJumpList.dll NppSaveAsAdmin.dll PluginManager.dll PyNPP.dll PythonScript.dll regrexplace.dll ReloadButton.dll SpellChecker.dll WebEditU.dll XMLTools.dll

**Comment by niccord** [comment]
Which version of Plugin Manager do you have installed?
Try to update it or to reinstall nodepad++, maybe.
I really don't know. This is the first time I heard of this issue.

**Comment by Zardozz** [comment]
Plugin Manager is 1.4.3
Notepad ++ is the latest

I went and installed a debugger and got the following output on crash:-
```
Tue Mar  7 15:16:02.802 2017 (UTC + 0:00): (c24.1a2c): Access violation - code c0000005 (first chance)
First chance exceptions are reported before any exception handling.
This exception may be expected and handled.
Loading symbols for 77210000 C:\WINDOWS\System32\USER32.dll ->   C:\WINDOWS\System32\USER32.dll
eax=00000000 ebx=00000000 ecx=092865b0 edx=00000000 esi=01331000 edi=092865b0
eip=092865b0 esp=014aa480 ebp=014aa4a0 iopl=0         nv up ei pl nz na pe nc
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00010206
<Unloaded_NppJumpList.dll>+0x65b0:
092865b0 ??              ???
```
I then re-instated Brackets Check and removed the NPPJumpList plugin and the crash on exit also stopped, so may be some interaction between the 2 plugins?


I then removed BracketsCheck and exited with the debug attached and it did not crash but the debugger still gave the same exception in NPPJumpList

I will investigate more with a clean install and just these 2 plugins

**Comment by niccord** [comment]
Very interesting, and very strange, too :)
Keep me updated 👍

**Comment by niccord** [comment]
@Zardozz do you have any update about this issue?

**Comment by Zardozz** [comment]
Moved to 64 bit version, so don't use Bracket Checks any more so no update
