### ISSUE TITLE
Plugin finds unbalanced less than (<) operator (C++)

### ISSUE THREAD

**Issue by nothingface0** [niccord/BracketsCheck#6]
For the code below

`for(is = 0; is < sl + 1; is++)`

the plugin finds unbalanced bracket at the less than operator. Is this intended for C++ source files?

**Comment by niccord** [comment]
The plugin was built to check large pieces of sql files, but it can used to check html/xml files, and other file formats.
It is not inteded to check source files.
I am going to add parametrization on which bracket the plugin should check.

Thanks!
p.s. my intention was to check < and > as brackets

**Comment by fotofrank** [comment]
Did you already have any luck with parametrization of this superb plugin?
There are some other plugins which can do the same, but somehow I prefer using this one.

**Comment by niccord** [comment]
Not yet, really, but I will soon, I promise :)

**Comment by niccord** [comment]
I fix the plugin as promised.
The plugin manager is not updated yet, but uninstalling-reinstalling the plugin will be updated to version 1.2 (despite plugin manager say it's version 1.0)

**Comment by nothingface0** [comment]
Excellent work! Thank you very much. :)

**Comment by fotofrank** [comment]
Works like a charm.
Thanks mate!
