### ISSUE TITLE
Not really saving settings between uses. 

### ISSUE THREAD

**Issue by jessebevil** [niccord/BracketsCheck#7]
So I seen that you show as saving settings between uses, and while it is true that the check boxes are in fact showing that the settings were saved, you are initializing each of the check boxes with a value of true, but it seems that you do a CommandMenuInit() which sets those check boxes. However, the variables aren't being updated in the process. So if I use the brackets check plugin and uncheck angle brackets for example, then close NPP it appears to save the settings in the Appdata, however on next load of notepad++ (and subsequently the plugin) it then updates the command menu, but not the variables themselves. 

I'm a bit new to C++/C# type stuff, but I made a change in CommandMenuInit() function 

```
internal static void CommandMenuInit()
        {
            PluginBase.InitiINI();
            PluginBase.SetCommand(0, "Check Brackets: All text", checkBracketsAll);
            PluginBase.SetCommand(1, "Check Brackets: Selected text", checkBracketsSelected);
            PluginBase.SetCommand(2, "", null); // ----------------------------------
            string checkRound = "Check round brackets";
            string checkSquare = "Check square brackets";
            string checkCurly = "Check curly brackets";
            string checkAngle = "Check angle brackets";
            PluginBase.SetCommand(3, checkRound, toggleCheckRoundBrackets, Win32.GetPrivateProfileInt(PluginName, checkRound, 1, PluginBase.IniFilePath) > 0);
            if (Win32.GetPrivateProfileInt(PluginName, checkRound, 1, PluginBase.IniFilePath) < 1) checkRoundBrackets = false;
            PluginBase.SetCommand(4, checkSquare, toggleCheckSquareBrackets, Win32.GetPrivateProfileInt(PluginName, checkSquare, 1, PluginBase.IniFilePath) > 0);
            if (Win32.GetPrivateProfileInt(PluginName, checkSquare, 1, PluginBase.IniFilePath) < 1) checkSquareBrackets = false;
            PluginBase.SetCommand(5, checkCurly, toggleCheckCurlyBrackets, Win32.GetPrivateProfileInt(PluginName, checkCurly, 1, PluginBase.IniFilePath) > 0);
            if (Win32.GetPrivateProfileInt(PluginName, checkCurly, 1, PluginBase.IniFilePath) < 1) checkCurlyBrackets = false;
            PluginBase.SetCommand(6, checkAngle, toggleCheckAngleBrackets, Win32.GetPrivateProfileInt(PluginName, checkAngle, 1, PluginBase.IniFilePath) > 0);
            if (Win32.GetPrivateProfileInt(PluginName, checkAngle, 1, PluginBase.IniFilePath) < 1) checkAngleBrackets = false;
        }
```
I can't test it however, as I get an error when trying to compile. 
```
1>D:\Downloads\BracketsCheck-master\BracketsCheck-master\BracketsCheck\DllExport\NppPlugin.DllExport.targets(8,5): error MSB4062: The "NppPlugin.DllExport.MSBuild.DllExportTask" task could not be loaded from the assembly D:\Downloads\BracketsCheck-master\BracketsCheck-master\BracketsCheck\DllExport\NppPlugin.DllExport.MSBuild.dll. Could not load file or assembly 'file:///D:\Downloads\BracketsCheck-master\BracketsCheck-master\BracketsCheck\DllExport\NppPlugin.DllExport.MSBuild.dll' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
```
 I check at the location and BracketsCheck\DllExport\NppPlugin.DllExport.targets file is present. I'm finding the file contains

```

<Project
  xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <UsingTask TaskName="NppPlugin.DllExport.MSBuild.DllExportTask"
             AssemblyFile="NppPlugin.DllExport.MSBuild.dll"/>
  <Target Name="AfterBuild"
          DependsOnTargets="GetFrameworkPaths"
          >
    <DllExportTask Platform="$(Platform)"
                   PlatformTarget="$(PlatformTarget)"
                   CpuType="$(CpuType)"
                   EmitDebugSymbols="$(DebugSymbols)"
                   DllExportAttributeAssemblyName="$(DllExportAttributeAssemblyName)"
                   DllExportAttributeFullName="$(DllExportAttributeFullName)"
                   Timeout="$(DllExportTimeout)"
                   KeyContainer="$(KeyContainerName)$(AssemblyKeyContainerName)"
                   KeyFile="$(KeyOriginatorFile)"
                   ProjectDirectory="$(MSBuildProjectDirectory)"
                   InputFileName="$(TargetPath)"
                   FrameworkPath="$(TargetedFrameworkDir);$(TargetFrameworkDirectory)"
                   LibToolPath="C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\bin\Hostx64\x64"
                   LibToolDllPath="$(DevEnvDir)"
                   SdkPath="C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools"/>
  </Target>
</Project>
```
Which would leave me to believe the function is present. Yet, I still receive this error. 
I'm using VS 2017 and I've never used C# prior to this. 

I see options for ANSI and Unicode release/debug, I've tried all 4 options, none of which appear to be working. I've edited the NppPlugin.DllExport.targets to point to correct paths for the SDKPath and LibToolPath, though I'm not sure of any of the other references it makes. 

If you could either update the current plugin to also update the variables settings (which are all initialized as true) so that I can download it from the PluginManager, or assist me with compiling this plugin it would be greatly appreciated. Thanks in advance.

**Comment by jessebevil** [comment]
Update - Was able to find the missing files and compile. Works as I was hoping it would and now sets the variable to the state saved in the INI to match the menu's check boxes. While I'm not a professional coder and realize that function is setup to Initialize the command menu and not the variables themselves. Adding it there works out well and now the variables are updated with the stored setting as well.

**Comment by chcg** [comment]
@niccord Any chance that you take a look at PR #4 which contains also the missing files and #8 related to this issue?

**Comment by niccord** [comment]
Hi @jessebevil, thanks for your feedback!
I'm going to fix it in a little different way than you suggest, anyway thanks a lot for your effort!

**Comment by SkyCharger001** [comment]
The problem still exists. (but in the **best** case you only need to release the latest version to the Plugins Admin)
