### ISSUE TITLE
Allow missing php closing tag

### ISSUE THREAD

**Issue by kkmuffme** [niccord/BracketsCheck#9]
For php it is normal (aka adviced) to leave off the closing ?> at the end of the file.

Thus it is not an error that there is 1 less ?> than <?php
Would be good, if it wouldn't report this as incorrect.

**Comment by niccord** [comment]
This is a very specific case and I am not sure this is something I want to achieve.
What if, instead, you put ?> at the end of your file before checking the brackets?

**Comment by kkmuffme** [comment]
Yeah possible, but it's just bad for usability.

But it's not that important since I switched to a IDE now anyway
